version: 2
jobs:
  build:
    docker:
      - image: "buildpack-deps:trusty"
    steps:
      - checkout
      - run: "echo Build worked"
  test:
    docker:
      - image: "buildpack-deps:trusty"
    steps:
      - checkout
      - run: "echo Build worked"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
