version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: echo Build worked
  test:
    steps:
      - checkout
      - run: echo Tests pass
workflows:
  version: 2
  build_and_test:
    docker:
    jobs:
      - build
      - test
